# 데이터 분석: 데이터를 분석하여 의사결정에 도움을 준다. 

- 통계 vs 데이터분석 vs 머신러닝
  - 통계: 데이터를 **요약, 해석하는** 수학(평균, 분산)
  - 데이터분석: **문제를 정의하고 인사이트 도출**(고객 구매 패턴 분석)
  - 머신러닝: 데이터를 학습하여 **예측**(스팸함 분류, 추천)

- DA 흐름
  1. 문제정의
  2. **데이터 수집**
  3. **데이터 정제(결측치, 이상치 처리)**
  4. **데이터 탐색-시각화(평균, 분포, 상관관계, 막대그래프, 히스토그램)**
  5. **통계 분석 및 해석**
  6. 결론 도출

- 데이터 분석 도구(시트 vs SQL vs Python)
  - 시트는 편함(ex 밀키트)
  - DB는 대용량 저장 및 처리(억단위) ex 냉장고
  - 시각화, 분석, 머신러닝 ex 요리

- 라이브러리(Numpy vs Pandas)
  - Numpy: 빠름(배열 연산)
  - Pandas: 표(DataFrame)-> Numpy 기반으로 만들어짐 
  - matplotlib: 시각화(그래프)
  - seaborn: 시각화 심화
  - scikit-learn: 머신러닝

In [ ]:
%pip install numpy

In [10]:
import numpy as np

array = np.array([1,2,3,4,5])
result = array *2
print(result)


[ 2  4  6  8 10]


In [12]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
np.array([1,2,3,4], dtype=float)

In [16]:
#0으로 채움
z1d = np.zeros(5)
z2d = np.zeros((2,3))
print(z1d, z2d)

# 1로 채움
o1d = np.ones(5)
o2d = np.ones((2, 3))
print(o1d, o2d)

# n으로 채움 -> 5칸 7로 채움
n1d = np.full(5, 7)



[0. 0. 0. 0. 0.] [[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.] [[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# range
range_arr = np.arange(0, 10, 2)
print(range_arr)
# 등간격 실수 배열
lin_space = np.linspace(0,1,5)
print(lin_space)

# 로그스케일
log_space = np.logspace(0,2,5)
print(log_space)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[  1.           3.16227766  10.          31.6227766  100.        ]


In [26]:
# 난수배열

random = np.random.rand(3, 3)
print(random)

# 정규 분표 난수
nomal = np.random.randn(3,3)
print(nomal)

# 정수 난수(0~9, 3*3)
int_random = np.random.randint(0, 10, (3, 3))
print(int_random)

[[0.00902458 0.36618817 0.20027892]
 [0.41842288 0.04740506 0.06030484]
 [0.62617662 0.75459653 0.33766833]]
[[ 2.2220069  -0.68784553 -1.76399155]
 [-0.5846757  -0.38353757 -1.15144495]
 [-0.24251389  1.15941511 -0.53373171]]
[[2 1 5]
 [8 7 7]
 [5 2 0]]


In [28]:
# 배열의 데이터 타입
# 데이터 타입 확인
arr = np.array([1,2,3], dtype=np.float64)
print(arr.dtype)

# 데이터 타입 지정 생성
f_arr = np.array([1,2,3], dtype=np.float64)
print(f_arr.dtype)

# 문자열-> 숫자
str_arr = np.array(['1.2', '2.3', '3.4'])
num_arr = str_arr.astype(float)
print(num_arr, num_arr.dtype)

float64
float64
[1.2 2.3 3.4] float64


In [32]:
# reshape -> 원본 그대로, 새로운 배열 만듬
# resize -> 원본을 바꿈

arr = np.arange(12)
reshape = arr.reshape(3,4)
print(reshape)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# 1~15 정수배열
print(np.arange(1, 16), np.array(range(1,16)))

# 0~9까지 홀수
print(np.arange)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [36]:
# N차원 -> 1차원
arr = np.array([[1,2,3], [4,5,6]])

r = arr.ravel() # 뷰 원본연결
f = arr.flatten() # 복사본

r[0] = 100
f[0] = -100

print(arr)
print(r, f)

[[100   2   3]
 [  4   5   6]]
[100   2   3   4   5   6] [-100    2    3    4    5    6]


In [37]:
import numpy as np

arr_2d = np.arange(16).reshape(4, 4)

print(arr_2d)

arr_2d[0:2, 0:2] = 0  # 0~1행, 0~1열 영역을 0으로 바꿈

print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  0  2  3]
 [ 0  0  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [38]:
# 다차원 배열 슬라이싱으로 변경
print(arr_2d)

arr_2d[0:2, 0:2] = 0

print(arr_2d)


[[ 0  0  2  3]
 [ 0  0  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  0  2  3]
 [ 0  0  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
# boolean 인덱싱
# 조건에 따라 배열 요소 선택
arr = np.arange(1, 6) 

# 마스킹 -> T/F로 바꿈
mask = arr > 3
print(mask, arr)

[False False False  True  True] [1 2 3 4 5]
