# 데이터 분석: 데이터를 분석하여 의사결정에 도움을 준다. 

- 통계 vs 데이터분석 vs 머신러닝
  - 통계: 데이터를 **요약, 해석하는** 수학(평균, 분산)
  - 데이터분석: **문제를 정의하고 인사이트 도출**(고객 구매 패턴 분석)
  - 머신러닝: 데이터를 학습하여 **예측**(스팸함 분류, 추천)

- DA 흐름
  1. 문제정의
  2. **데이터 수집**
  3. **데이터 정제(결측치, 이상치 처리)**
  4. **데이터 탐색-시각화(평균, 분포, 상관관계, 막대그래프, 히스토그램)**
  5. **통계 분석 및 해석**
  6. 결론 도출

- 데이터 분석 도구(시트 vs SQL vs Python)
  - 시트는 편함(ex 밀키트)
  - DB는 대용량 저장 및 처리(억단위) ex 냉장고
  - 시각화, 분석, 머신러닝 ex 요리

- 라이브러리(Numpy vs Pandas)
  - Numpy: 빠름(배열 연산)
  - Pandas: 표(DataFrame)-> Numpy 기반으로 만들어짐 
  - matplotlib: 시각화(그래프)
  - seaborn: 시각화 심화
  - scikit-learn: 머신러닝

In [41]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [42]:
python_list = [1, 2, 3, 4, 5]
# [2, 4, 6, 8, 10]
result = [x*2 for x in python_list]
print(result)

[2, 4, 6, 8, 10]


In [43]:
import numpy as np

array = np.array([1,2,3,4,5])
result = array *2
print(result)


[ 2  4  6  8 10]


In [44]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))
print('차원', arr.ndim)
print('형태', arr.shape)
print('크기', arr.size)

[1 2 3 4 5] <class 'numpy.ndarray'>
차원 1
형태 (5,)
크기 5


In [45]:

arr1d = np.array([1, 2, 3, 4, 5])
arr1d

array([1, 2, 3, 4, 5])

In [46]:
l2d = [
    [1, 2, 3],
    [4, 5, 6],
]
arr2d = np.array(l2d)

arr2d.ndim, arr2d.shape, arr2d.size, arr2d.dtype

(2, (2, 3), 6, dtype('int64'))

In [47]:
# 실수형 arr
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [48]:
#0으로 채움
z1d = np.zeros(5)
z2d = np.zeros((2,3))
print(z1d, z2d)

# 1로 채움
o1d = np.ones(5)
o2d = np.ones((2, 3))
print(o1d, o2d)

# n으로 채움 -> 5칸, 7로 채움
n1d = np.full(5, 7)
n2d = np.full((2, 3), 7)
print(n1d)
print(n2d)

# 빈칸이지만 먼저 만듬
empty = np.empty(3)
print(empty)



[0. 0. 0. 0. 0.] [[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.] [[1. 1. 1.]
 [1. 1. 1.]]
[7 7 7 7 7]
[[7 7 7]
 [7 7 7]]
[1. 2. 3.]


In [49]:
# range
range_arr = np.arange(0, 10, 2)
print(range_arr)
# 등간격 실수 배열
lin_space = np.linspace(0,1,5)
print(lin_space)

# 로그스케일
log_space = np.logspace(0,2,5)
print(log_space)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[  1.           3.16227766  10.          31.6227766  100.        ]


In [50]:

# 난수 배열

# 균등 분포 난수 (0~1) 사이를 균등활률 분포
random = np.random.rand(3, 3)  # 0 ~ 1 실수
print(random)

# *정규 분포 난수
normal = np.random.randn(3, 3)
print(normal)

# 정수 난수 (0 ~ 9, 3*3)
int_random = np.random.randint(0, 10, (3, 3))
print(int_random)

# 시드 설정(랜덤 재현 가능)
np.random.seed(42)  # 랜덤 상황 42 고정
np.random.rand(3)

[[0.31127058 0.92281246 0.41178948]
 [0.84179537 0.54738902 0.88523393]
 [0.50615688 0.28140602 0.99934819]]
[[-1.74382154 -0.23945938  0.04908526]
 [-1.01239638 -0.31685896 -0.00858794]
 [-1.6268486   0.73447195  1.10225798]]
[[7 8 2]
 [4 1 1]
 [3 7 2]]


array([0.37454012, 0.95071431, 0.73199394])

In [ ]:
# 배열의 데이터 타입
# 데이터 타입 확인
arr = np.array([1,2,3], dtype=np.float64)
print(arr.dtype)

# 데이터 타입 지정 생성
f_arr = np.array([1,2,3], dtype=np.float64)
print(f_arr.dtype)

# 데이터 타입 변경 (int -> float)
converted = arr.astype(np.float32)
print(converted.dtype)

# 문자열-> 숫자
str_arr = np.array(['1.2', '2.3', '3.4'])
num_arr = str_arr.astype(float)
print(num_arr, num_arr.dtype)

float64
float64
[1.2 2.3 3.4] float64


In [56]:
#배열 재구성
arr = np.arange(12)
print(arr)

reshaped2d = arr.reshape(3, 4)  # 3row * 4col
print(reshaped2d)

reshaped3d = arr.reshape(2, 2, 3)  # 2페이지, 2row * 3col
print(reshaped3d)

# 자동계산
auto1 = arr.reshape(3, -1)  # row 3개, col 알아서
auto2 = arr.reshape(-1, 6)  # row 알아서, col 6개

print(auto1)
print(auto2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [57]:
# 1차원 -> N차원
# reshape -> 원본 그대로, 새로운 배열 만드
# resize  -> 원본을 바꿈

arr = np.arange(12)
reshaped = arr.reshape(3, 4)  # 새로운 배열 리턴
print(reshaped)
print(arr)

arr.resize(3, 4)  # arr 이 바뀜
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [58]:
# N차원 -> 1차원
arr = np.array([[1, 2, 3], [4, 5, 6]])

r = arr.ravel()    # 뷰(원본 연결) -> 빨리 펼쳐서 보기
f = arr.flatten()  # 복사본       -> 안전하게 새로 만들어서 활용

r[0] = 100
f[0] = -100

print(arr)
print(r, f)

[[100   2   3]
 [  4   5   6]]
[100   2   3   4   5   6] [-100    2    3    4    5    6]


In [59]:
# 1 ~ 15 정수 배열 ( arange vs array(range) )
print(np.arange(1, 16), np.array(range(1, 16)))

# 0 ~ 9까지 홀수
print(np.arange(1, 10, 2))

# 0 ~ 3까지 균등 6등분(5구간) 배열
print(np.linspace(0, 3, 6))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[1 3 5 7 9]
[0.  0.6 1.2 1.8 2.4 3. ]


In [60]:
# 4 * 4 단위 행렬(identity matrix) -> 대각선1, 나머지0
print(np.eye(4))

# 3 * 4 사이즈의 1로 가득찬 int 배열
print(np.ones((3, 4), dtype=int))

# 2 * 3 * 4 사이즈 0~1 난수 배열  
np.random.rand(2, 3, 4)      # 인자로 차원 지정 -> 오래된 버전에서 주로 씀
np.random.random((2, 3, 4))  # 튜플로 차원 지정 -> 최신 버전에서 주로 씀

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


array([[[0.51423444, 0.59241457, 0.04645041, 0.60754485],
        [0.17052412, 0.06505159, 0.94888554, 0.96563203],
        [0.80839735, 0.30461377, 0.09767211, 0.68423303]],

       [[0.44015249, 0.12203823, 0.49517691, 0.03438852],
        [0.9093204 , 0.25877998, 0.66252228, 0.31171108],
        [0.52006802, 0.54671028, 0.18485446, 0.96958463]]])

In [61]:
arr = np.array([10, 20, 30, 40, 50])
# 접근
print(arr[0], arr[2], arr[-1], arr[-2])

# 변경
arr[0] = 100
print(arr)

10 30 50 40
[100  20  30  40  50]


In [62]:

# arr_2d = np.array(range(1, 10)).reshape(3, 3)
arr_2d = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
# Numpy 에서만 지원
arr_2d[0, 0]  # arr_2d[0][0] -> r 0, c 0
arr_2d[1, 1]

arr_2d[1]  # 행 접근

# 변경
arr_2d[0, 0] = 100
arr_2d

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [63]:

# 슬라이싱
arr = np.arange(10)
print(
    arr[2:5],
    arr[:5],
    arr[5:]
)

print(
    arr[1:8:2],
    arr[::2]
)

print(
    arr[::-1],
    arr[7:2:-1]
)

# 슬라이싱으로 일괄 변경 (Python X)
arr[3:6] = 100
print(arr)

[2 3 4] [0 1 2 3 4] [5 6 7 8 9]
[1 3 5 7] [0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0] [7 6 5 4 3]
[  0   1   2 100 100 100   6   7   8   9]


In [64]:
# 다차원 배열 슬라이싱
arr_2d = np.arange(1, 13).reshape(3, -1)
print(arr_2d)

# row(행) 슬라이싱 -> 0, 1 idx 행
print(arr_2d[0:2])

# col(열) 슬라이싱 -> 모든 행의 idx 1, 2 열
print(arr_2d[:, 1:3])

# row / col 동시 슬라이싱 -> 1, 2 행 / 0, 1 열 
print(arr_2d[1:3, 0:2])

# 간격지정  -> 행/열 모두 2간격
print(arr_2d[::2, ::2])  

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[ 5  6]
 [ 9 10]]
[[ 1  3]
 [ 9 11]]


In [67]:
# 2차원 배열 불리언 인덱싱
arr_2d = np.arange(1, 10).reshape(3, 3)

mask = arr_2d > 5

# 원본 matrix 형태 없음. True 로 필터된 애들만 Vector로 나옴
print(arr_2d[mask])  
print(arr_2d[arr_2d < 6])

# 조건에 맞는 행만 선택
row_mask = np.array([True, False, True])
print(arr_2d)
print(arr_2d[row_mask])  # row T, F, T -> 0, 2 row 만 뽑음

[6 7 8 9]
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]


In [66]:
# boolean 인덱싱
# 조건에 따라 배열 요소 선택

arr = np.arange(1, 6)  # [1, 2, 3, 4, 5]

# 마스킹 -> T/F 로 바꿈
mask = arr > 3
print(mask, arr)

# 마스킹 배열로 필터링
print(arr[mask])

# 직접 조건
print(arr[arr > 3])

# 다중조건
print(arr[ (arr > 2) & (arr < 5) ])  # and
print(arr[ (arr == 1) | (arr > 3) ])  # or

[False False False  True  True] [1 2 3 4 5]
[4 5]
[4 5]
[3 4]
[1 4 5]


In [65]:

# 다차원 배열 슬라이싱으로 변경
print(arr_2d)

# 부분 배열 일괄 변경
arr_2d[0:2, 0:2] = 0
print(arr_2d)

# 열 교체 (모든행, idx 3열) -> 벡터 ->  교체 -> 원본 matrix 의 열이 바뀜
arr_2d[:, 3] = [100, 200, 300]

print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 0  0  3  4]
 [ 0  0  7  8]
 [ 9 10 11 12]]
[[  0   0   3 100]
 [  0   0   7 200]
 [  9  10  11 300]]


In [32]:
# reshape -> 원본 그대로, 새로운 배열 만듬
# resize -> 원본을 바꿈

arr = np.arange(12)
reshape = arr.reshape(3,4)
print(reshape)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# 1~15 정수배열
print(np.arange(1, 16), np.array(range(1,16)))

# 0~9까지 홀수
print(np.arange)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [36]:
# N차원 -> 1차원
arr = np.array([[1,2,3], [4,5,6]])

r = arr.ravel() # 뷰 원본연결
f = arr.flatten() # 복사본

r[0] = 100
f[0] = -100

print(arr)
print(r, f)

[[100   2   3]
 [  4   5   6]]
[100   2   3   4   5   6] [-100    2    3    4    5    6]


In [37]:
import numpy as np

arr_2d = np.arange(16).reshape(4, 4)

print(arr_2d)

arr_2d[0:2, 0:2] = 0  # 0~1행, 0~1열 영역을 0으로 바꿈

print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  0  2  3]
 [ 0  0  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [38]:
# 다차원 배열 슬라이싱으로 변경
print(arr_2d)

arr_2d[0:2, 0:2] = 0

print(arr_2d)


[[ 0  0  2  3]
 [ 0  0  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  0  2  3]
 [ 0  0  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [40]:

# boolean 인덱싱
# 조건에 따라 배열 요소 선택

arr = np.arange(1, 6)  # [1, 2, 3, 4, 5]

# 마스킹 -> T/F 로 바꿈
mask = arr > 3
print(mask, arr)

# 마스킹 배열로 필터링
print(arr[mask])

# 직접 조건
print(arr[arr > 3])

# 다중조건
print(arr[ (arr > 2) & (arr < 5) ])  # and
print(arr[ (arr == 1) | (arr > 3) ])  # or

[False False False  True  True] [1 2 3 4 5]


In [68]:
# Fancy 인덱싱
arr = np.arange(10, 60, 10)
print(arr)
# arr[1, 2]  -> arr[1][2]
print(arr[ [1, 2] ])  # -> arr[1], arr[2] 를 뽑아라
print(arr[ [0, 2, 3] ])  # -> arr[0], arr[2], arr[3] 만 가져와라

print(arr[[0, 0, 1, 1, 2, 3, 4, 2, 1]])
print(arr[[4, 2, 3, 1, 0]])

[10 20 30 40 50]
[20 30]
[10 30 40]
[10 10 20 20 30 40 50 30 20]
[50 30 40 20 10]


In [69]:
arr_2d = np.arange(1, 10).reshape(3, 3)
print(arr_2d)

print(arr_2d[0])  # row 0

# 특정 행만 선택
print(arr_2d[ [0, 2] ])  # row 0, 2

print()

# 행과, 열 동시에 선택
print(
    arr_2d[  # (0, 0), (1, 2), (2, 1) 순서로 벡터 만듬
        [0, 1, 2],
        [0, 2, 1]
    ]
)

# 행렬의 열을 순서 바꾸기
print(
    arr_2d[
        :,         # 모든 행
        [2, 0, 1]  # 열 idx를 이렇게 바꿔라
    ]
)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[[1 2 3]
 [7 8 9]]

[1 6 8]
[[3 1 2]
 [6 4 5]
 [9 7 8]]


In [ ]:
# 10부터 20까지의 정수 배열 생성
arr = np.arange(10, 21)
print('원본', arr)

# 문제1: 배열의 첫 번째, 세 번째, 마지막 요소 출력
print(
    arr[0]
    arr[2]
    arr[-1]
)

# 문제2: 인덱스 2부터 5까지 요소 출력
print[0:6]
# 문제3: 처음부터 5번째 요소까지 모든 짝수 인덱스 요소 출력

# 문제4: 배열의 요소를 역순으로 출력

원본 [10 11 12 13 14 15 16 17 18 19 20]


In [71]:
# 3 * 4 matrix
matrix = np.arange(12).reshape(3, 4)
print('원본', matrix)

# 문제1: (1,2) 위치의 요소 출력

# 문제2: 두 번째 행 전체 출력

# 문제3: 마지막 열 전체 출력

# 문제4: 첫 번째와 세 번째 행의 두 번째와 네 번째 열 요소만 추출

원본 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [72]:
arr = np.arange(1, 21)
print('원본', arr)

# 문제1: 5의 배수만 선택하여 출력

# 문제2: 3보다 크고 15보다 작은 요소 선택

# 문제3: 7의 배수이거나 홀수인 요소 선택

원본 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [74]:
# 
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

print(a ** 2)
print(a ** b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]
[    1    64  2187 65536]


In [ ]:
a = np.array([True, False, True, False])
b = np.array([False, True, True, False])

# 논리연산
# AND
print(a & b)
# OR
print(a | b)
# NOT
print(~a)

In [ ]:
# 배열 생성
arr = np.array([1, 2, 3, 4, 5])

# 스칼라 덧셈
print(arr + 10)     # [11 12 13 14 15]

# 스칼라 뺄셈
print(arr - 1)      # [0 1 2 3 4]

# 스칼라 곱셈
print(arr * 2)      # [2 4 6 8 10]

# 스칼라 나눗셈
print(arr / 2)      # [0.5 1.  1.5 2.  2.5]

# 스칼라 거듭제곱
print(arr ** 2)     # [ 1  4  9 16 25]

# 스칼라 비교
print(arr > 3)      # [False False False  True  True]
print(arr == 2)     # [False  True False False False]                                                                

In [ ]:
# 2차원 배열
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# 스칼라 연산
print(arr_2d + 10)
# [[11 12 13]
#  [14 15 16]]

print(arr_2d * 3)
# [[ 3  6  9]
#  [12 15 18]]

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

# 행렬 + 행 벡터
print(matrix + vector)

# 열 벡터 브로드캐스팅
col_vec = np.array(
    [
        [100],
        [200]
    ]
)
print(matrix + col_vec)

In [ ]:
# 브로드 캐스팅 가능한 경우

A = np.ones((3, 2))       # 3x2 배열
B = np.ones((2,))         # 길이 2인 1차원 배열 (1x2로 해석) (행벡터)
C = np.ones((3, 1))       # 3x1 배열 (사실상 열벡터)

print("A + B 형태:", (A + B).shape)  # (3, 2) - B는 각 행에 브로드캐스팅
print(A + B)


print("A + C 형태:", (A + C).shape)  # (3, 2) - C는 각 열에 브로드캐스팅
print(A + C)


In [75]:
# 연산중 데이터 자동 변환
# 테스트 배열
x = np.array([0, np.pi/4, np.pi/2, np.pi])
y = np.array([1, 2, 3, 4])

# 삼각함수
print("sin(x) =", np.sin(x))  # [0., 0.70710678, 1., 0.]
print("cos(x) =", np.cos(x))  # [1., 0.70710678, 0., -1.]
print("tan(x) =", np.tan(x))  # [0., 1., 16331239353195370., 0.]

# 역삼각함수
print("arcsin(sin(x)) =", np.arcsin(np.sin(x)))

# 지수와 로그
print("exp(y) =", np.exp(y))  # [2.71828183, 7.3890561, 20.08553692, 54.59815003]
print("log(y) =", np.log(y))  # [0., 0.69314718, 1.09861229, 1.38629436]
print("log10(y) =", np.log10(y))  # [0., 0.30103, 0.47712125, 0.60205999]
print("log2(y) =", np.log2(y))  # [0., 1., 1.58496250, 2.]

# 제곱근과 거듭제곱
print("sqrt(y) =", np.sqrt(y))  # [1., 1.41421356, 1.73205081, 2.]
print("power(y, 2) =", np.power(y, 2))  # [1, 4, 9, 16]

# 절대값과 부호
z = np.array([-2, -1, 0, 1, 2])
print("abs(z) =", np.abs(z))  # [2 1 0 1 2]
print("sign(z) =", np.sign(z))  # [-1 -1  0  1  1]

# 소수점 처리
w = np.array([1.2, 2.7, 3.5, 4.9])
print("floor(w) =", np.floor(w))  # [1. 2. 3. 4.] (내림)
print("ceil(w) =", np.ceil(w))   # [2. 3. 4. 5.] (올림)
print("round(w) =", np.round(w))  # [1. 3. 4. 5.] (반올림)
print("trunc(w) =", np.trunc(w))  # [1. 2. 3. 4.] (소수점 버림)

sin(x) = [0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
cos(x) = [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]
tan(x) = [ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.22464680e-16]
arcsin(sin(x)) = [0.00000000e+00 7.85398163e-01 1.57079633e+00 1.22464680e-16]
exp(y) = [ 2.71828183  7.3890561  20.08553692 54.59815003]
log(y) = [0.         0.69314718 1.09861229 1.38629436]
log10(y) = [0.         0.30103    0.47712125 0.60205999]
log2(y) = [0.        1.        1.5849625 2.       ]
sqrt(y) = [1.         1.41421356 1.73205081 2.        ]
power(y, 2) = [ 1  4  9 16]
abs(z) = [2 1 0 1 2]
sign(z) = [-1 -1  0  1  1]
floor(w) = [1. 2. 3. 4.]
ceil(w) = [2. 3. 4. 5.]
round(w) = [1. 3. 4. 5.]
trunc(w) = [1. 2. 3. 4.]


In [79]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 기본 집계
print("합계:", np.sum(arr))          # 45
print("평균:", np.mean(arr))         # 5.0
print("최소값:", np.min(arr))        # 1
print("최대값:", np.max(arr))        # 9
print("표준편차:", np.std(arr))      # 2.581988897471611
print("분산:", np.var(arr))          # 6.666666666666667

# 축을 따라 집계
print("행별 합계:", np.sum(arr, axis=1))  # [ 6 15 24]
print("열별 합계:", np.sum(arr, axis=0))  # [12 15 18]
print("행별 평균:", np.mean(arr, axis=1))  # [2. 5. 8.]
print("열별 평균:", np.mean(arr, axis=0))  # [4. 5. 6.]
print("행별 최소값:", np.min(arr, axis=1))  # [1 4 7]
print("열별 최소값:", np.min(arr, axis=0))  # [1 2 3]



합계: 45
평균: 5.0
최소값: 1
최대값: 9
표준편차: 2.581988897471611
분산: 6.666666666666667
행별 합계: [ 6 15 24]
열별 합계: [12 15 18]
행별 평균: [2. 5. 8.]
열별 평균: [4. 5. 6.]
행별 최소값: [1 4 7]
열별 최소값: [1 2 3]


In [ ]:
arr = np.array([1,2,3,4])
print(arr)

#row vector->[[1,2,3,4]]


# col vector -> [[1],[2],[3],[4]]




In [80]:
# 누적 합계 (cumulative sum)
print("누적 합계:", np.cumsum(arr))  # [ 1  3  6 10 15 21 28 36 45]
print("행별 누적 합계:")
print(np.cumsum(arr, axis=1))
# [[ 1  3  6]
#  [ 4  9 15]
#  [ 7 15 24]]

# 누적 곱 (cumulative product)
print("누적 곱:", np.cumprod(arr))  # [1 2 6 24 120 720 5040 40320 362880]

# 중앙값 (median)
print("중앙값:", np.median(arr))        # 5.0
print("행별 중앙값:", np.median(arr, axis=1))  # [2. 5. 8.]
print("열별 중앙값:", np.median(arr, axis=0))  # [4. 5. 6.]

# 백분위수 (percentile)
print("25% 백분위수:", np.percentile(arr, 25))  # 3.0
print("50% 백분위수:", np.percentile(arr, 50))  # 5.0 (중앙값과 동일)
print("75% 백분위수:", np.percentile(arr, 75))  # 7.0

# 가중 평균 (weighted average)
weights = np.array([0.1, 0.3, 0.6])  # 가중치
data = np.array([2, 5, 8])
print("가중 평균:", np.average(data, weights=weights))  # 6.1

누적 합계: [ 1  3  6 10 15 21 28 36 45]
행별 누적 합계:
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
누적 곱: [     1      2      6     24    120    720   5040  40320 362880]
중앙값: 5.0
행별 중앙값: [2. 5. 8.]
열별 중앙값: [4. 5. 6.]
25% 백분위수: 3.0
50% 백분위수: 5.0
75% 백분위수: 7.0
가중 평균: 6.5


In [81]:
# 샘플 배열
arr = np.arange(12)  # [ 0  1  2  3  4  5  6  7  8  9 10 11]

# 균등 분할
print("3개로 균등 분할:")
print(np.split(arr, 3))  # [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

# 위치 지정 분할
print("위치 지정 분할 (인덱스 3, 8 기준):")
print(np.split(arr, [3, 8]))  # [array([0, 1, 2]), array([3, 4, 5, 6, 7]), array([ 8,  9, 10, 11])]

# 2차원 배열 분할
arr_2d = np.arange(16).reshape(4, 4)
print("2차원 배열:")
print(arr_2d)

# 행 방향 분할
print("행 방향 분할:")
print(np.split(arr_2d, 2, axis=0))  # 2개 배열로 (각 2x4)
print(np.vsplit(arr_2d, 2))  # 동일한 결과

# 열 방향 분할
print("열 방향 분할:")
print(np.split(arr_2d, 2, axis=1))  # 2개 배열로 (각 4x2)
print(np.hsplit(arr_2d, 2))  # 동일한 결과

3개로 균등 분할:
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
위치 지정 분할 (인덱스 3, 8 기준):
[array([0, 1, 2]), array([3, 4, 5, 6, 7]), array([ 8,  9, 10, 11])]
2차원 배열:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
행 방향 분할:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
열 방향 분할:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
